
# This file was generated by 'versioneer.py' (0.10) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '39a1b01398f1d932630f722a540a5020c6c07422'
version_full = '39a1b01398f1d932630f722a540a5020c6c07422'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

